### ISSUE TITLE
User can create an entry

### ISSUE THREAD

**Issue by amyaitran** [jsygo/week-planner#1]
## ✅ Task List
- [x] Add a form for creating an entry.
- [x] Make all inputs of the journal entry form `required`.
- [x] Create a modal for the form.
- [x] Listen for `'submit'` events on the journal entry form and:
  - [ ] Put the form's input values into a new object.
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [ ] Prepend the new object to the entries in the data model.
  - [ ] Reset the form inputs.
- [ ] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [ ] Verify that each new entry receives an incrementing `entryId`.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
